### ISSUE TITLE
ERROR: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ashishmg-gds** [Azure/arm-deploy#93]
Hi Team,

Looks like a code issue to me. I get the following error when trying to deploy my DataFactory ARM Template.

```
Validating template...
Warning: ERROR: 'str' object has no attribute 'get'

Warning: Template validation failed.
Creating deployment...
Error: ERROR: 'str' object has no attribute 'get'

Error: Deployment failed.
```
I validated the ARMTemplate also, just to check, But all seems to be good.

Im using the `azure-data-factory-utilities` npm package method to create the ARMTemplate

**Comment by t-dedah** [comment]
Hi @ashishmg-gds Is the template working fine if deployed using azure cli?
If yes, will it be possible to share the template for us to replicate the issue?

**Comment by ashishmg-gds** [comment]
@t-dedah  I wont be able to share the template but, Im getting the same issue when trying via azure cli.
I added `--debug` to the deployment creation command and got following stacktrace:

```
DEBUG: cli.azure.cli.core.util: attempting to read file ./ArmTemplate/ArmTemplate/ARMTemplateForFactory.json as utf-8-sig
DEBUG: cli.azure.cli.core.util: invalid syntax (<unknown>, line 1)
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 538, in deploy_arm_template_at_resource_group
    return _deploy_arm_template_at_resource_group(cmd=cmd,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 567, in _deploy_arm_template_at_resource_group
    deployment_properties = _prepare_deployment_properties_unmodified(cmd, 'resourceGroup', template_file=template_file,
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 1000, in _prepare_deployment_properties_unmodified
    parameters = _get_missing_parameters(parameters, template_obj, _prompt_for_parameters, no_prompt)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 263, in _get_missing_parameters
    prompt_parameters = prompt_fn(missing)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/command_modules/resource/custom.py", line 189, in _prompt_for_parameters
    description = metadata.get('description', description)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 109, in handle_template_based_exception
    raise CLIError(ex.inner_exception.error.message)
AttributeError: 'AttributeError' object has no attribute 'inner_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/usr/local/lib/python3.9/site-packages/azure/cli/core/commands/arm.py", line 114, in handle_template_based_exception
    raise CLIError(ex)
knack.util.CLIError: 'str' object has no attribute 'get'
```

**Comment by ashishmg-gds** [comment]
I also exported the ARM template from my Data Factory and compared with the generated one. Seems to be Identical

**Comment by davyrod** [comment]
@ashishmg-gds I was facing this same issue and I got past the error by taking the parameters with empty values in the 'ARMTemplateParametersForFactory.json' file, and adding those to the 'parameters:' attribute in the GitHub Action declaration.

**Comment by t-dedah** [comment]
@ashishmg-gds As you are getting the same error with azure cli that means the issue is with azure cli and not this action specifically. So which version of azure-cli are you using ?

**Comment by ashishmg-gds** [comment]
@t-dedah  I used both latest and 2.30.0 version as well

**Comment by t-dedah** [comment]
Hi @ashishmg-gds Are you still facing this issue?
Did you try the solutions suggested here https://github.com/Azure/arm-deploy/issues/93#issuecomment-1016861114 or https://github.com/Azure/arm-deploy/issues/68#issuecomment-1000896837

**Comment by t-dedah** [comment]
Hi @ashishmg-gds Please reopen the issue if you are still facing this issue

**Comment by UGangal-Insight** [comment]
I am facing the same issue

**Comment by PavanBadiger** [comment]
i am facing same issue
